{% set name = "hunspell" %}
{% set version = "1.7.1" %}
{% set sha256 = "6e3557624c608b3e6525b8bd277706db4f5a857c28fdb3cfa8d0d2b67776da8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hunspell/hunspell/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  has_prefix_files:
    - bin/hunspell

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gettext
    - readline
  run:
    - gettext
    - readline

test:
  commands:
    - hunspell --help

about:
  home: http://hunspell.github.io/
  license: MPL 1.1/GPL 2.0/LGPL 2.1
  license_family: GPL
  license_file: COPYING
  summary: The most popular spellchecking library.
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  doc_url: http://hunspell.github.io/
  dev_url: https://github.com/hunspell/hunspell

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
