{% set version = "1.7.0" %}
{% set posix = "m2-" if win else "" %}
{% set native = "m2w64-" if win else "" %}

package:
  name: hunspell
  version: {{ version }}

source:
  url: https://github.com/hunspell/hunspell/archive/v{{ version }}.tar.gz
  sha256: bb27b86eb910a8285407cf3ca33b62643a02798cf2eef468c0a74f6c3ee6bc8a

build:
  number: 1002

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - make  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}autoconf  # [win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}bash  # [win]
    - {{ posix }}gcc-libs  # [win]
    - {{ posix }}grep  # [win]
    - {{ posix }}libtool  # [win]
    - {{ posix }}m4  # [win]
    - {{ posix }}make  # [win]
    - {{ posix }}sed  # [win]
  host:
    - gettext  # [unix]
    - readline  # [unix]
    - {{ posix }}ncurses  # [win]
    - {{ posix }}libreadline  # [win]
    - libiconv  # [win]
  run:
    - gettext  # [unix]
    - readline  # [unix]
    - {{ posix }}ncurses  # [win]
    - {{ posix }}libreadline  # [win]
    - libiconv  # [win]
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - hunspell --help

about:
  home: https://hunspell.github.io
  license: MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: The most popular spellchecking library.
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  doc_url: https://hunspell.github.io
  dev_url: https://github.com/hunspell/hunspell

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - bollwyvl
